/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuyang_code_controllers_NDK */

#ifndef _Included_com_liuyang_code_controllers_NDK
#define _Included_com_liuyang_code_controllers_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuyang_code_controllers_NDK
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liuyang_code_controllers_NDK_stringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
